#! /usr/bin/bash


# Insert prolog into the output file
echo "# abook addressbook file" > $2
echo ""                         >> $2
echo "[format]"                 >> $2
echo "program=abook"            >> $2
echo "version=0.6.1"            >> $2
echo ""                         >> $2
echo ""                         >> $2


# Put every vcard object on one line
cat $1 | tr '\n' ' ' | sed 's/BEGIN:VCARD //g; s/END:VCARD /\n/g' > tmp1


# Remove lines without a (vcard) EMAIL tag as they are not interesting for an
# addressbook that is used for Neomutt
cat tmp1 | sed -n '/EMAIL/p' > tmpX

# Look for the (vcard) FN tag and replace it with "name="
# Remove everything before FN, but leave the rest of the line alone.
cat tmpX | sed 's/.\+ FN:\(.\+\) \(\S\?\S:.\+\)/name=\1<NAME_END>\2/g' > tmp2


# Look for the (vcard) EMAIL tag and replace it with "email="
cat tmp2 | sed 's/EMAIL;\S\+:\(\S\+\)/email=\1<EMAIL_END>/g' > tmp3


# Clean up between <NAME_END> and "email="
cat tmp3 | sed 's/\(<NAME_END>\)\S\+ \(.\+\)/\1\2/g' > tmp4


# Remove multiple "email=" markers
# People with more than one email address have multiple "email=" marker, but
# they should just have one and the email addresses should be separated by a
# ",".
cat tmp4 | sed 's/<EMAIL_END> email=/,/g' > tmp5

